//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job.PricesWF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WfcpLog_ET_RETURN
    {
        public int id { get; set; }
        public int DocumentoId { get; set; }
        public System.DateTime fecha_insert { get; set; }
        public string IDENTIFICADOR { get; set; }
        public string MESSAGE { get; set; }
        public int NUMBER { get; set; }
        public string TYPE { get; set; }
    }
}
