//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job.PricesWF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WfcpDocumento_Estatus
    {
        public int id { get; set; }
        public int DocumentoId { get; set; }
        public int EstatusId { get; set; }
        public string usuario { get; set; }
        public System.DateTime fecha_estatus { get; set; }
        public string metodo_autorizacion { get; set; }
        public int RolId { get; set; }
    
        public virtual WfcpDocumento WfcpDocumento { get; set; }
        public virtual WfcpEstatus WfcpEstatus { get; set; }
        public virtual WfcpRol WfcpRol { get; set; }
    }
}
