//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Root.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WFOCEntities : DbContext
    {
        public WFOCEntities()
            : base("name=WFOCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WfcpMoneda> WfcpMoneda { get; set; }
        public virtual DbSet<WfcpRol> WfcpRol { get; set; }
        public virtual DbSet<WfcpUsuario> WfcpUsuario { get; set; }
        public virtual DbSet<WfcpUsuarioInRol> WfcpUsuarioInRol { get; set; }
        public virtual DbSet<WfcpDocumento> WfcpDocumento { get; set; }
        public virtual DbSet<WfcpWorkflow> WfcpWorkflow { get; set; }
        public virtual DbSet<WfcpDocumento_Estatus> WfcpDocumento_Estatus { get; set; }
        public virtual DbSet<WfcpEstatus> WfcpEstatus { get; set; }
        public virtual DbSet<WfcpNuevaPartida> WfcpNuevaPartida { get; set; }
        public virtual DbSet<WfcpLog_ET_RETURN> WfcpLog_ET_RETURN { get; set; }
        public virtual DbSet<WfcpCambioPrecio> WfcpCambioPrecio { get; set; }
        public virtual DbSet<WfcpTipoProcuracion> WfcpTipoProcuracion { get; set; }
        public virtual DbSet<WfcpUnidadMedida> WfcpUnidadMedida { get; set; }
        public virtual DbSet<WfcpDocumento_Proveedor> WfcpDocumento_Proveedor { get; set; }
    
        public virtual int spSendMail_WfcpDocumento(string recipientes, string ccp_recipientes, string asunto, string html)
        {
            var recipientesParameter = recipientes != null ?
                new ObjectParameter("recipientes", recipientes) :
                new ObjectParameter("recipientes", typeof(string));
    
            var ccp_recipientesParameter = ccp_recipientes != null ?
                new ObjectParameter("ccp_recipientes", ccp_recipientes) :
                new ObjectParameter("ccp_recipientes", typeof(string));
    
            var asuntoParameter = asunto != null ?
                new ObjectParameter("asunto", asunto) :
                new ObjectParameter("asunto", typeof(string));
    
            var htmlParameter = html != null ?
                new ObjectParameter("html", html) :
                new ObjectParameter("html", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSendMail_WfcpDocumento", recipientesParameter, ccp_recipientesParameter, asuntoParameter, htmlParameter);
        }
    }
}
