//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Root.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WfcpEstatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WfcpEstatus()
        {
            this.WfcpDocumento_Estatus = new HashSet<WfcpDocumento_Estatus>();
        }
    
        public int id { get; set; }
        public int WorkflowId { get; set; }
        public string nombre { get; set; }
        public bool valido { get; set; }
        public bool activo { get; set; }
        public string descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WfcpDocumento_Estatus> WfcpDocumento_Estatus { get; set; }
        public virtual WfcpWorkflow WfcpWorkflow { get; set; }
    }
}
