//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Root.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WfcpDocumento_Proveedor
    {
        public int id { get; set; }
        public long documento_oc { get; set; }
        public string LIFNR { get; set; }
        public string NAME_VENDOR { get; set; }
    }
}
