//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Root.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WfcpCambioPrecio
    {
        public int id { get; set; }
        public int DocumentoId { get; set; }
        public long documento_oc { get; set; }
        public string no_parte { get; set; }
        public double precio { get; set; }
        public int MonedaId { get; set; }
        public System.DateTime fecha_punto_quiebre { get; set; }
        public string justificacion { get; set; }
        public string usuario { get; set; }
        public System.DateTime fecha_actualizacion { get; set; }
        public Nullable<int> ITEM_NO { get; set; }
        public Nullable<double> KTMGN { get; set; }
        public string MEINS { get; set; }
        public Nullable<double> NETPBR { get; set; }
        public Nullable<double> PEINH { get; set; }
        public Nullable<System.DateTime> fecha_validacion { get; set; }
    
        public virtual WfcpDocumento WfcpDocumento { get; set; }
        public virtual WfcpMoneda WfcpMoneda { get; set; }
    }
}
